---
title: "extend_plot"
author: "Joshua"
date: "15/01/2021"
output: 
  pdf_document:
    keep_tex: true
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = F)
rm(list=ls())
library('forecast')
library('smooth')
library('beanplot')
library('pastecs')
library('scales')
library('ggplot2')

load('extend_result.Rdata')

iter<-200
```

#Time series_1
```{r series_1_ppl}
x_axis<-c(40,120,480,1200,4800)
for (i in 1:20) {
  y_40<-c(Reduce("+",para_combin_1[[i]][[1]][[1]])[1]/iter,Reduce("+",para_combin_1[[i]][[1]][[2]])[1]/iter,
        Reduce("+",para_combin_1[[i]][[1]][[3]])[1]/iter)
  y_120<-c(Reduce("+",para_combin_1[[i]][[2]][[1]])[1]/iter,Reduce("+",para_combin_1[[i]][[2]][[2]])[1]/iter,
         Reduce("+",para_combin_1[[i]][[2]][[3]])[1]/iter)
  y_480<-c(Reduce("+",para_combin_1[[i]][[3]][[1]])[1]/iter,Reduce("+",para_combin_1[[i]][[3]][[2]])[1]/iter,
         Reduce("+",para_combin_1[[i]][[3]][[3]])[1]/iter)
  y_1200<-c(Reduce("+",para_combin_1[[i]][[4]][[1]])[1]/iter,Reduce("+",para_combin_1[[i]][[4]][[2]])[1]/iter,
         Reduce("+",para_combin_1[[i]][[4]][[3]])[1]/iter)
  y_4800<-c(Reduce("+",para_combin_1[[i]][[5]][[1]])[1]/iter,Reduce("+",para_combin_1[[i]][[5]][[2]])[1]/iter,
         Reduce("+",para_combin_1[[i]][[5]][[3]])[1]/iter)
  y_axis<-c(y_40,y_120,y_480,y_1200,y_4800)
  mac<-matrix(y_axis,nrow = 3,ncol = 5)
  mac<-t(mac)
  rownames(mac)<-c('40','120','480','1200','4800')
  colnames(mac)<-c("DJ","QR","IMEO")
  par(mar=c(par('mar')[1:3], 0)) 
  plot.new()
  l <- legend(0, 0, bty='n',c( "DJ","QR","IMEO"),plot=FALSE, pch=2:4,col=2:4)
  w <- grconvertX(l$rect$w, to='ndc') - grconvertX(0, to='ndc')
  par(omd=c(0, 1-w, 0, 1))
  matplot(mac, type = c("b"),pch=2:4,col = 2:4,xaxt = "n",yaxt = "n"
          ,xlab = 'data length',ylab = 'percetage profit loss') 
  axis(1, at=1:5, labels=x_axis)
  axis(2, at=pretty(y_axis), lab=paste0(pretty(y_axis) * 100, "%"), las=TRUE)
  legend(par('usr')[2], par('usr')[4], bty='n', xpd=NA
        ,c("DJ","QR","IMEO"), pch=2:4,col=2:4)
}


```


```{r series_1_sl}
x_axis<-c(40,120,480,1200,4800)
for (i in 1:20) {
  y_40<-c(Reduce("+",para_combin_1[[i]][[1]][[1]])[2]/iter,Reduce("+",para_combin_1[[i]][[1]][[2]])[2]/iter,
        Reduce("+",para_combin_1[[i]][[1]][[3]])[2]/iter)
  y_120<-c(Reduce("+",para_combin_1[[i]][[2]][[1]])[2]/iter,Reduce("+",para_combin_1[[i]][[2]][[2]])[2]/iter,
         Reduce("+",para_combin_1[[i]][[2]][[3]])[2]/iter)
  y_480<-c(Reduce("+",para_combin_1[[i]][[3]][[1]])[2]/iter,Reduce("+",para_combin_1[[i]][[3]][[2]])[2]/iter,
         Reduce("+",para_combin_1[[i]][[3]][[3]])[2]/iter)
  y_1200<-c(Reduce("+",para_combin_1[[i]][[4]][[1]])[2]/iter,Reduce("+",para_combin_1[[i]][[4]][[2]])[2]/iter,
         Reduce("+",para_combin_1[[i]][[4]][[3]])[2]/iter)
  y_4800<-c(Reduce("+",para_combin_1[[i]][[5]][[1]])[2]/iter,Reduce("+",para_combin_1[[i]][[5]][[2]])[2]/iter,
         Reduce("+",para_combin_1[[i]][[5]][[3]])[2]/iter)
  y_axis<-c(y_40,y_120,y_480,y_1200,y_4800)
  mac<-matrix(y_axis,nrow = 3,ncol = 5)
  mac<-t(mac)
  rownames(mac)<-c('40','120','480','1200','4800')
  colnames(mac)<-c("DJ","QR","IMEO")
  par(mar=c(par('mar')[1:3], 0)) 
  plot.new()
  l <- legend(0, 0, bty='n',c( "DJ","QR","IMEO"),plot=FALSE, pch=2:4,col=2:4)
  w <- grconvertX(l$rect$w, to='ndc') - grconvertX(0, to='ndc')
  par(omd=c(0, 1-w, 0, 1))
  matplot(mac, type = c("b"),pch=2:4,col = 2:4,xaxt = "n",yaxt = "n"
          ,xlab = 'data length',ylab = 'percetage profit loss') 
  axis(1, at=1:5, labels=x_axis)
  axis(2, at=pretty(y_axis), lab=paste0(pretty(y_axis) * 100, "%"), las=TRUE)
  legend(par('usr')[2], par('usr')[4], bty='n', xpd=NA
        ,c("DJ","QR","IMEO"), pch=2:4,col=2:4)
}


```



#Time series_2
```{r series_2_ppl}
x_axis<-c(40,120,480,1200,4800)
for (i in 1:20) {
  y_40<-c(Reduce("+",para_combin_2[[i]][[1]][[1]])[1]/iter,Reduce("+",para_combin_2[[i]][[1]][[2]])[1]/iter,
        Reduce("+",para_combin_2[[i]][[1]][[3]])[1]/iter)
  y_120<-c(Reduce("+",para_combin_2[[i]][[2]][[1]])[1]/iter,Reduce("+",para_combin_2[[i]][[2]][[2]])[1]/iter,
         Reduce("+",para_combin_2[[i]][[2]][[3]])[1]/iter)
  y_480<-c(Reduce("+",para_combin_2[[i]][[3]][[1]])[1]/iter,Reduce("+",para_combin_2[[i]][[3]][[2]])[1]/iter,
         Reduce("+",para_combin_2[[i]][[3]][[3]])[1]/iter)
  y_1200<-c(Reduce("+",para_combin_2[[i]][[4]][[1]])[1]/iter,Reduce("+",para_combin_2[[i]][[4]][[2]])[1]/iter,
         Reduce("+",para_combin_2[[i]][[4]][[3]])[1]/iter)
  y_4800<-c(Reduce("+",para_combin_2[[i]][[5]][[1]])[1]/iter,Reduce("+",para_combin_2[[i]][[5]][[2]])[1]/iter,
         Reduce("+",para_combin_2[[i]][[5]][[3]])[1]/iter)
  y_axis<-c(y_40,y_120,y_480,y_1200,y_4800)
  mac<-matrix(y_axis,nrow = 3,ncol = 5)
  mac<-t(mac)
  rownames(mac)<-c('40','120','480','1200','4800')
  colnames(mac)<-c("DJ","QR","IMEO")
  par(mar=c(par('mar')[1:3], 0)) 
  plot.new()
  l <- legend(0, 0, bty='n',c( "DJ","QR","IMEO"),plot=FALSE, pch=2:4,col=2:4)
  w <- grconvertX(l$rect$w, to='ndc') - grconvertX(0, to='ndc')
  par(omd=c(0, 1-w, 0, 1))
  matplot(mac, type = c("b"),pch=2:4,col = 2:4,xaxt = "n",yaxt = "n"
          ,xlab = 'data length',ylab = 'percetage profit loss') 
  axis(1, at=1:5, labels=x_axis)
  axis(2, at=pretty(y_axis), lab=paste0(pretty(y_axis) * 100, "%"), las=TRUE)
  legend(par('usr')[2], par('usr')[4], bty='n', xpd=NA
        ,c("DJ","QR","IMEO"), pch=2:4,col=2:4)
}


```


```{r series_2_sl}
x_axis<-c(40,120,480,1200,4800)
for (i in 1:20) {
  y_40<-c(Reduce("+",para_combin_2[[i]][[1]][[1]])[2]/iter,Reduce("+",para_combin_2[[i]][[1]][[2]])[2]/iter,
        Reduce("+",para_combin_2[[i]][[1]][[3]])[2]/iter)
  y_120<-c(Reduce("+",para_combin_2[[i]][[2]][[1]])[2]/iter,Reduce("+",para_combin_2[[i]][[2]][[2]])[2]/iter,
         Reduce("+",para_combin_2[[i]][[2]][[3]])[2]/iter)
  y_480<-c(Reduce("+",para_combin_2[[i]][[3]][[1]])[2]/iter,Reduce("+",para_combin_2[[i]][[3]][[2]])[2]/iter,
         Reduce("+",para_combin_2[[i]][[3]][[3]])[2]/iter)
  y_1200<-c(Reduce("+",para_combin_2[[i]][[4]][[1]])[2]/iter,Reduce("+",para_combin_2[[i]][[4]][[2]])[2]/iter,
         Reduce("+",para_combin_2[[i]][[4]][[3]])[2]/iter)
  y_4800<-c(Reduce("+",para_combin_2[[i]][[5]][[1]])[2]/iter,Reduce("+",para_combin_2[[i]][[5]][[2]])[2]/iter,
         Reduce("+",para_combin_2[[i]][[5]][[3]])[2]/iter)
  y_axis<-c(y_40,y_120,y_480,y_1200,y_4800)
  mac<-matrix(y_axis,nrow = 3,ncol = 5)
  mac<-t(mac)
  rownames(mac)<-c('40','120','480','1200','4800')
  colnames(mac)<-c("DJ","QR","IMEO")
  par(mar=c(par('mar')[1:3], 0)) 
  plot.new()
  l <- legend(0, 0, bty='n',c( "DJ","QR","IMEO"),plot=FALSE, pch=2:4,col=2:4)
  w <- grconvertX(l$rect$w, to='ndc') - grconvertX(0, to='ndc')
  par(omd=c(0, 1-w, 0, 1))
  matplot(mac, type = c("b"),pch=2:4,col = 2:4,xaxt = "n",yaxt = "n"
          ,xlab = 'data length',ylab = 'percetage profit loss') 
  axis(1, at=1:5, labels=x_axis)
  axis(2, at=pretty(y_axis), lab=paste0(pretty(y_axis) * 100, "%"), las=TRUE)
  legend(par('usr')[2], par('usr')[4], bty='n', xpd=NA
        ,c("DJ","QR","IMEO"), pch=2:4,col=2:4)
}


```



#Time series_3
```{r series_3_ppl}
x_axis<-c(40,120,480,1200,4800)
for (i in 1:20) {
  y_40<-c(Reduce("+",para_combin_3[[i]][[1]][[1]])[1]/iter,Reduce("+",para_combin_3[[i]][[1]][[2]])[1]/iter,
        Reduce("+",para_combin_3[[i]][[1]][[3]])[1]/iter)
  y_120<-c(Reduce("+",para_combin_3[[i]][[2]][[1]])[1]/iter,Reduce("+",para_combin_3[[i]][[2]][[2]])[1]/iter,
         Reduce("+",para_combin_3[[i]][[2]][[3]])[1]/iter)
  y_480<-c(Reduce("+",para_combin_3[[i]][[3]][[1]])[1]/iter,Reduce("+",para_combin_3[[i]][[3]][[2]])[1]/iter,
         Reduce("+",para_combin_3[[i]][[3]][[3]])[1]/iter)
  y_1200<-c(Reduce("+",para_combin_3[[i]][[4]][[1]])[1]/iter,Reduce("+",para_combin_3[[i]][[4]][[2]])[1]/iter,
         Reduce("+",para_combin_3[[i]][[4]][[3]])[1]/iter)
  y_4800<-c(Reduce("+",para_combin_3[[i]][[5]][[1]])[1]/iter,Reduce("+",para_combin_3[[i]][[5]][[2]])[1]/iter,
         Reduce("+",para_combin_3[[i]][[5]][[3]])[1]/iter)
  y_axis<-c(y_40,y_120,y_480,y_1200,y_4800)
  mac<-matrix(y_axis,nrow = 3,ncol = 5)
  mac<-t(mac)
  rownames(mac)<-c('40','120','480','1200','4800')
  colnames(mac)<-c("DJ","QR","IMEO")
  par(mar=c(par('mar')[1:3], 0)) 
  plot.new()
  l <- legend(0, 0, bty='n',c( "DJ","QR","IMEO"),plot=FALSE, pch=2:4,col=2:4)
  w <- grconvertX(l$rect$w, to='ndc') - grconvertX(0, to='ndc')
  par(omd=c(0, 1-w, 0, 1))
  matplot(mac, type = c("b"),pch=2:4,col = 2:4,xaxt = "n",yaxt = "n"
          ,xlab = 'data length',ylab = 'percetage profit loss') 
  axis(1, at=1:5, labels=x_axis)
  axis(2, at=pretty(y_axis), lab=paste0(pretty(y_axis) * 100, "%"), las=TRUE)
  legend(par('usr')[2], par('usr')[4], bty='n', xpd=NA
        ,c("DJ","QR","IMEO"), pch=2:4,col=2:4)
}


```


```{r series_3_sl}
x_axis<-c(40,120,480,1200,4800)
for (i in 1:20) {
  y_40<-c(Reduce("+",para_combin_3[[i]][[1]][[1]])[2]/iter,Reduce("+",para_combin_3[[i]][[1]][[2]])[2]/iter,
        Reduce("+",para_combin_3[[i]][[1]][[3]])[2]/iter)
  y_120<-c(Reduce("+",para_combin_3[[i]][[2]][[1]])[2]/iter,Reduce("+",para_combin_3[[i]][[2]][[2]])[2]/iter,
         Reduce("+",para_combin_3[[i]][[2]][[3]])[2]/iter)
  y_480<-c(Reduce("+",para_combin_3[[i]][[3]][[1]])[2]/iter,Reduce("+",para_combin_3[[i]][[3]][[2]])[2]/iter,
         Reduce("+",para_combin_3[[i]][[3]][[3]])[2]/iter)
  y_1200<-c(Reduce("+",para_combin_3[[i]][[4]][[1]])[2]/iter,Reduce("+",para_combin_3[[i]][[4]][[2]])[2]/iter,
         Reduce("+",para_combin_3[[i]][[4]][[3]])[2]/iter)
  y_4800<-c(Reduce("+",para_combin_3[[i]][[5]][[1]])[2]/iter,Reduce("+",para_combin_3[[i]][[5]][[2]])[2]/iter,
         Reduce("+",para_combin_3[[i]][[5]][[3]])[2]/iter)
  y_axis<-c(y_40,y_120,y_480,y_1200,y_4800)
  mac<-matrix(y_axis,nrow = 3,ncol = 5)
  mac<-t(mac)
  rownames(mac)<-c('40','120','480','1200','4800')
  colnames(mac)<-c("DJ","QR","IMEO")
  par(mar=c(par('mar')[1:3], 0)) 
  plot.new()
  l <- legend(0, 0, bty='n',c( "DJ","QR","IMEO"),plot=FALSE, pch=2:4,col=2:4)
  w <- grconvertX(l$rect$w, to='ndc') - grconvertX(0, to='ndc')
  par(omd=c(0, 1-w, 0, 1))
  matplot(mac, type = c("b"),pch=2:4,col = 2:4,xaxt = "n",yaxt = "n"
          ,xlab = 'data length',ylab = 'percetage profit loss') 
  axis(1, at=1:5, labels=x_axis)
  axis(2, at=pretty(y_axis), lab=paste0(pretty(y_axis) * 100, "%"), las=TRUE)
  legend(par('usr')[2], par('usr')[4], bty='n', xpd=NA
        ,c("DJ","QR","IMEO"), pch=2:4,col=2:4)
}


```


#Time series_4
```{r series_4_ppl}
x_axis<-c(40,120,480,1200,4800)
for (i in 1:20) {
  y_40<-c(Reduce("+",para_combin_4[[i]][[1]][[1]])[1]/iter,Reduce("+",para_combin_4[[i]][[1]][[2]])[1]/iter,
        Reduce("+",para_combin_4[[i]][[1]][[3]])[1]/iter)
  y_120<-c(Reduce("+",para_combin_4[[i]][[2]][[1]])[1]/iter,Reduce("+",para_combin_4[[i]][[2]][[2]])[1]/iter,
         Reduce("+",para_combin_4[[i]][[2]][[3]])[1]/iter)
  y_480<-c(Reduce("+",para_combin_4[[i]][[3]][[1]])[1]/iter,Reduce("+",para_combin_4[[i]][[3]][[2]])[1]/iter,
         Reduce("+",para_combin_4[[i]][[3]][[3]])[1]/iter)
  y_1200<-c(Reduce("+",para_combin_4[[i]][[4]][[1]])[1]/iter,Reduce("+",para_combin_4[[i]][[4]][[2]])[1]/iter,
         Reduce("+",para_combin_4[[i]][[4]][[3]])[1]/iter)
  y_4800<-c(Reduce("+",para_combin_4[[i]][[5]][[1]])[1]/iter,Reduce("+",para_combin_4[[i]][[5]][[2]])[1]/iter,
         Reduce("+",para_combin_4[[i]][[5]][[3]])[1]/iter)
  y_axis<-c(y_40,y_120,y_480,y_1200,y_4800)
  mac<-matrix(y_axis,nrow = 3,ncol = 5)
  mac<-t(mac)
  rownames(mac)<-c('40','120','480','1200','4800')
  colnames(mac)<-c("DJ","QR","IMEO")
  par(mar=c(par('mar')[1:3], 0)) 
  plot.new()
  l <- legend(0, 0, bty='n',c( "DJ","QR","IMEO"),plot=FALSE, pch=2:4,col=2:4)
  w <- grconvertX(l$rect$w, to='ndc') - grconvertX(0, to='ndc')
  par(omd=c(0, 1-w, 0, 1))
  matplot(mac, type = c("b"),pch=2:4,col = 2:4,xaxt = "n",yaxt = "n"
          ,xlab = 'data length',ylab = 'percetage profit loss') 
  axis(1, at=1:5, labels=x_axis)
  axis(2, at=pretty(y_axis), lab=paste0(pretty(y_axis) * 100, "%"), las=TRUE)
  legend(par('usr')[2], par('usr')[4], bty='n', xpd=NA
        ,c("DJ","QR","IMEO"), pch=2:4,col=2:4)
}


```


```{r series_4_sl}
x_axis<-c(40,120,480,1200,4800)
for (i in 1:20) {
  y_40<-c(Reduce("+",para_combin_4[[i]][[1]][[1]])[2]/iter,Reduce("+",para_combin_4[[i]][[1]][[2]])[2]/iter,
        Reduce("+",para_combin_4[[i]][[1]][[3]])[2]/iter)
  y_120<-c(Reduce("+",para_combin_4[[i]][[2]][[1]])[2]/iter,Reduce("+",para_combin_4[[i]][[2]][[2]])[2]/iter,
         Reduce("+",para_combin_4[[i]][[2]][[3]])[2]/iter)
  y_480<-c(Reduce("+",para_combin_4[[i]][[3]][[1]])[2]/iter,Reduce("+",para_combin_4[[i]][[3]][[2]])[2]/iter,
         Reduce("+",para_combin_4[[i]][[3]][[3]])[2]/iter)
  y_1200<-c(Reduce("+",para_combin_4[[i]][[4]][[1]])[2]/iter,Reduce("+",para_combin_4[[i]][[4]][[2]])[2]/iter,
         Reduce("+",para_combin_4[[i]][[4]][[3]])[2]/iter)
  y_4800<-c(Reduce("+",para_combin_4[[i]][[5]][[1]])[2]/iter,Reduce("+",para_combin_4[[i]][[5]][[2]])[2]/iter,
         Reduce("+",para_combin_4[[i]][[5]][[3]])[2]/iter)
  y_axis<-c(y_40,y_120,y_480,y_1200,y_4800)
  mac<-matrix(y_axis,nrow = 3,ncol = 5)
  mac<-t(mac)
  rownames(mac)<-c('40','120','480','1200','4800')
  colnames(mac)<-c("DJ","QR","IMEO")
  par(mar=c(par('mar')[1:3], 0)) 
  plot.new()
  l <- legend(0, 0, bty='n',c( "DJ","QR","IMEO"),plot=FALSE, pch=2:4,col=2:4)
  w <- grconvertX(l$rect$w, to='ndc') - grconvertX(0, to='ndc')
  par(omd=c(0, 1-w, 0, 1))
  matplot(mac, type = c("b"),pch=2:4,col = 2:4,xaxt = "n",yaxt = "n"
          ,xlab = 'data length',ylab = 'percetage profit loss') 
  axis(1, at=1:5, labels=x_axis)
  axis(2, at=pretty(y_axis), lab=paste0(pretty(y_axis) * 100, "%"), las=TRUE)
  legend(par('usr')[2], par('usr')[4], bty='n', xpd=NA
        ,c("DJ","QR","IMEO"), pch=2:4,col=2:4)
}


```